/*
 * @Description:
 * @Author:
 * @Date: 2020-05-15 09:54:01
 * @LastEditTime: 2021-05-28 17:37:12
 * @LastEditors: Please set LastEditors
 */
import Vue from "vue";
import {
    Button,
    Rate,
    NavBar,
    ShareSheet,
    Toast,
    CollapseItem,
    Tab,
    Collapse,
    Tabs,
    Icon,
    DatetimePicker,
    Overlay,
    Picker,
    RadioGroup,
    Radio,
    Search,
    IndexBar,
    IndexAnchor,
    SwipeCell,
    cellGroup,
    cell,
    DropdownMenu,
    DropdownItem,
    Switch,
    Tag,
    Popup,
    PasswordInput,
    NumberKeyboard,
    Area,
    ActionSheet,
    Checkbox,
    CheckboxGroup,
    Row,
    Col,
    Dialog,
    Step,
    Steps,
    Uploader,
    Field,
    Circle,
    Card,
    List,
    PullRefresh,
    CellGroup,
    Image,
    Grid,
    GridItem,
    Progress,
    Divider,
    Swipe,
    SwipeItem,
} from "vant";
Vue.use(Button);
Vue.use(NavBar);
Vue.use(Toast);
Vue.use(Tab);
Vue.use(Tabs);
Vue.use(Icon);
Vue.use(DatetimePicker);
Vue.use(Overlay);
Vue.use(Picker);
Vue.use(RadioGroup);
Vue.use(Radio);
Vue.use(Search);
Vue.use(IndexBar);
Vue.use(IndexAnchor);
Vue.use(SwipeCell);
Vue.use(cellGroup);
Vue.use(cell);
Vue.use(DropdownMenu);
Vue.use(DropdownItem);
Vue.use(Switch);
Vue.use(Tag);
Vue.use(Popup);
Vue.use(PasswordInput);
Vue.use(NumberKeyboard);
Vue.use(Area);
Vue.use(ActionSheet);
Vue.use(Checkbox);
Vue.use(CheckboxGroup);
Vue.use(Row);
Vue.use(Col);
Vue.use(Dialog);
Vue.use(Step);
Vue.use(Steps);
Vue.use(Uploader);
Vue.use(ShareSheet);
Vue.use(Collapse);
Vue.use(CollapseItem);
Vue.use(Field);
Vue.use(Circle);
Vue.use(Card);
Vue.use(Rate);
Vue.use(List);
Vue.use(PullRefresh);
Vue.use(CellGroup);
Vue.use(Image);
Vue.use(Grid);
Vue.use(GridItem);
Vue.use(Progress);
Vue.use(Divider);
Vue.use(Swipe);
Vue.use(SwipeItem);
